version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "wenealves"
      POSTGRES_PASSWORD: "04091605"
      POSTGRES_DB: "heroes"
    networks:
      - pgnet

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "wenealves"
      MONGO_INITDB_ROOT_PASSWORD: "04091605"
      MONGO_INITDB_DATABASE: "heroes"
    networks:
      - mongonet

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - pgnet

  mongoclient:
    image: mongoclient/mongoclient:4.0.0
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
    environment:
      STARTUP_DELAY: 10
      MONGO_URL: "mongodb://wenealves:04091605@mongo:27017/admin"
    networks:
      - mongonet

networks:
  pgnet:
  mongonet:
